apiVersion: v1
kind: Service
metadata:
  name: dbshepherd
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dbshepherd
  type: LoadBalancer
